/*
This file is part of Giswater
The program is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.
*/


SET search_path = SCHEMA_NAME, public, pg_catalog;

-- common
ALTER TABLE inp_dscenario_controls ADD observ text NULL;
ALTER TABLE inp_dscenario_inlet ADD observ text NULL;
ALTER TABLE inp_dscenario_junction ADD observ text NULL;
ALTER TABLE inp_dscenario_frpump ADD observ text NULL;


DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT formname, COALESCE(MAX(layoutorder), 0) AS max_layoutorder
        FROM config_form_fields
        WHERE formname LIKE 'inp_dscenario_%'
        GROUP BY formname
    LOOP
        INSERT INTO config_form_fields (
            formname, formtype, tabname, columnname, layoutname, layoutorder,
            "datatype", widgettype, "label", tooltip, placeholder,
            ismandatory, isparent, iseditable, isautoupdate, isfilter,
            dv_querytext, dv_orderby_id, dv_isnullvalue, dv_parent_id,
            dv_querytext_filterc, stylesheet, widgetcontrols, widgetfunction,
            linkedobject, hidden, web_layoutorder
        ) VALUES (
            r.formname, 'form_feature', 'tab_none', 'observ', NULL, r.max_layoutorder + 1,
            'string', 'textarea', 'Observ', 'observ', NULL,
            false, false, true, false, NULL,
            NULL, NULL, NULL, NULL,
            NULL, NULL, NULL, NULL,
            NULL, false, NULL
        );
    END LOOP;
END $$;

INSERT INTO config_param_user (parameter, value, cur_user)
VALUES ('utils_language_ui', '{"status":true, "lang":"en_US"}', current_user)
ON CONFLICT (parameter, cur_user) DO NOTHING;

DO $patch$
BEGIN
    IF to_regprocedure('gw_fct_get_utils_language_ui()') IS NOT NULL THEN
        ALTER FUNCTION gw_fct_get_utils_language_ui() VOLATILE;
    END IF;
END $patch$;



INSERT INTO sys_param_user (
    id, formname, descript, sys_role, "label", dv_querytext, isenabled, layoutorder,
    project_type, isparent, isautoupdate, "datatype", widgettype, ismandatory,
    layoutname, iseditable, "source", dv_isnullvalue
)
VALUES (
    'multilang_language', 'config',
    'UI language for database messages when multilang schema is enabled',
    'role_basic', 'UI language',
    'SELECT ''default'' AS id, ''Default'' AS idval UNION ALL SELECT id, idval FROM multilang.cat_language',
    false, 6, 'utils', false, false, 'string', 'combo', false,
    'lyt_basic', true, 'core', false
)
ON CONFLICT (id) DO UPDATE SET
    dv_querytext = EXCLUDED.dv_querytext,
    dv_isnullvalue = false,
    isenabled = CASE
        WHEN to_regclass('multilang.cat_language') IS NULL THEN false
        ELSE sys_param_user.isenabled
    END;


INSERT INTO config_param_user (parameter, value, cur_user)
SELECT
    'multilang_language',
    lower(replace(value::json->>'lang', '-', '_')),
    cur_user
FROM config_param_user
WHERE parameter = 'utils_language_ui'
  AND value IS NOT NULL
  AND btrim(value) <> ''
  AND value::json->>'lang' IS NOT NULL
  AND btrim(value::json->>'lang') <> ''
ON CONFLICT (parameter, cur_user) DO UPDATE SET value = EXCLUDED.value;


DELETE FROM config_param_user WHERE parameter = 'utils_language_ui';
DELETE FROM sys_param_user WHERE id = 'utils_language_ui';


UPDATE sys_param_user
SET
    dv_querytext = 'SELECT ''default'' AS id, ''Default'' AS idval UNION ALL SELECT id, idval FROM multilang.cat_language',
    dv_isnullvalue = false,
    isenabled = CASE
        WHEN to_regclass('multilang.cat_language') IS NULL THEN false
        ELSE isenabled
    END
WHERE id = 'multilang_language';


ALTER TABLE cat_feature ADD custom_code_autofill bool DEFAULT false NULL;
ALTER TABLE config_mapzones ADD custom_code_autofill bool DEFAULT false NULL;


-- Graph inundation materialization (avoid large GeoJSON temporal layers in QGIS)
CREATE TABLE IF NOT EXISTS anl_graphinundation (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fid integer NOT NULL DEFAULT 710,
	cur_user character varying(30) DEFAULT CURRENT_USER::text NOT NULL,
	mapzone text,
	arc_id character varying(16) NOT NULL,
	start_vid bigint,
	node_1 character varying(16),
	node_2 character varying(16),
	arc_type character varying(30),
	arccat_id character varying(30),
	state integer,
	state_type integer,
	is_operative boolean,
	mapzone_id text,
	old_mapzone_id text,
	descript text,
	timestep timestamp without time zone,
	the_geom public.geometry(LineString, SRID_VALUE)
);

CREATE INDEX IF NOT EXISTS anl_graphinundation_cur_user_fid_idx
	ON anl_graphinundation USING btree (cur_user, fid);
CREATE INDEX IF NOT EXISTS anl_graphinundation_cur_user_timestep_idx
	ON anl_graphinundation USING btree (cur_user, timestep);
CREATE INDEX IF NOT EXISTS anl_graphinundation_the_geom_idx
	ON anl_graphinundation USING gist (the_geom);

CREATE OR REPLACE VIEW v_anl_graphinundation AS
SELECT
	id,
	fid,
	cur_user,
	mapzone,
	arc_id,
	start_vid,
	node_1,
	node_2,
	arc_type,
	arccat_id,
	state,
	state_type,
	is_operative,
	mapzone_id,
	old_mapzone_id,
	descript,
	timestep,
	the_geom
FROM anl_graphinundation
WHERE cur_user = CURRENT_USER::text;

INSERT INTO sys_table (id, descript, sys_role, alias, "source")
VALUES
	('anl_graphinundation', 'Table with graph inundation temporal analysis arcs', 'role_om', NULL, 'core'),
	('v_anl_graphinundation', 'View with graph inundation temporal analysis arcs for current user', 'role_edit', 'Graphanalytics tstep process', 'core')
ON CONFLICT (id) DO NOTHING;

INSERT INTO config_table (id, style, group_layer)
VALUES ('v_anl_graphinundation', 0, 'GW Temporal Layers')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, "source", fprocess_type, function_name, active)
VALUES (710, 'Graph inundation temporal analysis', 'utils', 'core', 'Function process', '[gw_fct_getgraphinundation]', true)
ON CONFLICT (fid) DO NOTHING;

UPDATE sys_function
SET descript = 'Materializes graph inundation temporal arcs into anl_graphinundation and returns the layer metadata for QGIS'
WHERE id = 3338;
